export const userFormLabels = [
  {
    errorMessage: "El nombre es obligatorio",
    htmlFor: "firstname",
    name: "firstname",
    label: "Nombre",
    autoComplete: "given-name",
    type: "text",
    isRequired: true,
  },
  {
    errorMessage: "",
    htmlFor: "second_name",
    name: "second_name",
    label: "Segundo Nombre",
    autoComplete: "given-name",
    type: "text",
    isRequired: false,
  },
  {
    errorMessage: "El apellido es obligatorio",
    htmlFor: "lastname",
    name: "lastname",
    label: "Primer Apellido",
    autoComplete: "family-name",
    type: "text",
    isRequired: true,
  },
  {
    errorMessage: "",
    htmlFor: "second_lastname",
    name: "second_lastname",
    label: "Segundo Apellido",
    autoComplete: "family-name",
    type: "text",
    isRequired: false,
  },
  {
    errorMessage: "El numero de telefono es obligatorio",
    htmlFor: "phone",
    name: "phone",
    label: "Telefono",
    autoComplete: "tel",
    placeholder: "(305) 555-5555",
    type: "text",
    isRequired: true,
  },
  {
    errorMessage: "",
    htmlFor: "email",
    name: "email",
    label: "Correo Electronico",
    autoComplete: "email",
    type: "email",
    isRequired: false,
  },
];
